# Generated by Django 6.0.2 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('Sukuma', 'sukuma'), ('Spinach', 'spinach'), ('Cabbage', 'cabbage')], default='Sukuma', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='e.g., bundle, piece', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
