# Generated by Django 6.0.2 on 2026-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
