# Generated by Django 6.0.2 on 2026-02-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_produce_quantity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='quantity_available',
        ),
    ]
