# Generated by Django 6.0.2 on 2026-03-11 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_produce_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
